buildscript {
    // Update ke 2.1.0 sesuai saran terminal lo tadi
    ext.kotlin_version = '2.1.0' 
    repositories {
        google()
        mavenCentral()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:8.2.1'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        classpath 'com.google.gms:google-services:4.4.1'
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.layout.buildDirectory.value(rootProject.layout.buildDirectory.dir("../../build").get())

subprojects {
    project.layout.buildDirectory.value(rootProject.layout.buildDirectory.dir(project.name).get())
    
    // UPDATE FIX: Paksa semua library pakai SDK 36 biar gak komplain AAR Metadata
    project.afterEvaluate {
        if (project.hasProperty('android')) {
            project.android {
                compileSdk = 36
                buildToolsVersion = "36.0.0"
            }
        }
    }

    project.evaluationDependsOn(":app")
}

tasks.register("clean", Delete) {
    delete rootProject.layout.buildDirectory
}